name: "Bug Report"
description: Describe the bug with a screenshot
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: Describe the bug with a screenshot

  - type: checkboxes
    attributes:
      label: Checks
      options:
        - label: >
            I tried to fix the problem myself by reading the contents of the error in the console.
        
  - type: textarea
    attributes:
      label: Problem Description
      description: A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: Add screenshots from [console](https://github.com/JoyHak/customize-vivaldi-buttons/blob/main/screenshots/console.png).
    validations:
      required: true
