name: "Improvement"
description: Share an idea on how to improve the code or suggest smth new.
labels: ["improvement"]

body:
  - type: textarea
    attributes:
      label: Description
      description: Describe your idea/how your code works
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code
      description: Suggest your code.
      render: js
    validations:
      required: false
      
  - type: textarea
    attributes:
      label: Line number
      description: [Point](https://github.com/JoyHak/customize-vivaldi-buttons/blob/d788dac5f8d478e1479e623f5827313603820f72/public.js#L8) to the corresponding file and line number(s) which could be improved. Click on the [line number](https://github.com/JoyHak/customize-vivaldi-buttons/blob/d788dac5f8d478e1479e623f5827313603820f72/public.js#L8) in GitHub to create an anchored link to the corresponding code section
    validations:
      required: false    