name: "Question"
description: Ask me something.
labels: ["question"]

body:
  - type: checkboxes
    attributes:
      label: Checks
      options:
        - label: >
           This is not a bug/code review.
        
  - type: textarea
    attributes:
      label: Question
      description: What do you want to ask?
    validations:
      required: true